// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Pub = (function(Pub) {
    var Glass, HalfPint, Pint;
    Glass = (function() {
      function Glass(quantity) {
        this._quantity = quantity;
      }

      Glass.prototype._consume = function(quantityToConsume) {
        if (this._quantity <= 0) {
          return;
        }
        if (this._quantity > quantityToConsume) {
          return this._quantity -= quantityToConsume;
        } else {
          return this._quantity = 0;
        }
      };

      Glass.prototype.drink = function() {
        return this._consume(1);
      };

      Glass.prototype.quaff = function() {
        return this._consume(4);
      };

      Glass.prototype.downInOne = function() {
        return this._consume(this._quantity);
      };

      Glass.prototype.getQuantity = function() {
        return this._quantity;
      };

      return Glass;

    })();
    Pint = (function(_super) {
      __extends(Pint, _super);

      function Pint() {
        Pint.__super__.constructor.call(this, 20);
      }

      return Pint;

    })(Glass);
    Pub.Pint = Pint;
    HalfPint = (function(_super) {
      __extends(HalfPint, _super);

      function HalfPint() {
        HalfPint.__super__.constructor.call(this, 10);
      }

      return HalfPint;

    })(Glass);
    Pub.HalfPint = HalfPint;
    return Pub;
  })(window.Pub || {});

}).call(this);
